### ISSUE TITLE
Extension in Opera GX

### ISSUE THREAD

**Issue by Chadstain** [mlsof21/voice-dim#1]
The extension doesnt work for me in opera gx and i have checked everything and it still dont work

**Comment by mlsof21** [comment]
This is going to require some type of polyfill. I'll have to work on this to figure out.

**Comment by mlsof21** [comment]
Even going the Firefox route that I've attempted (record audio locally, then send that off for transcription, wait for the results), I can't get Opera GX to work. I don't believe there's an extension out there that does audio recording that works in Opera GX as well. Not sure if there's a solution, but I don't want to continue to pursue something on a small usage browser. If I ever see an update about Web Speech or recording audio in GX, then maybe, but for now, I'm closing this issue.
