### ISSUE TITLE
Switching characters affects item movement until refresh

### ISSUE THREAD

**Issue by mlsof21** [mlsof21/voice-dim#22]
When you've recently switched characters, pretty much every command involving weapons will fail. This is more related to DIM than anything.

**Comment by delphiactual** [comment]
auto-refresh should be coming back soon

**Comment by mlsof21** [comment]
Yep, I just saw that.

**Comment by mlsof21** [comment]
Auto-refresh has been re-enabled in DIM. This doesn't solve the issue if you immediately try to move items before DIM refreshes, but it's doesn't need to be handled by the extension.
