### ISSUE TITLE
Not working in Brave 

### ISSUE THREAD

**Issue by ctrlcmdshft** [mlsof21/voice-dim#3]
I've tried getting this working on 2 different brave browsers, a fresh public install with no other extension, and beta that I use daily. When set up then hitting the hot key you see it trigger them mic by the icon on the DIM tab it flashes once and goes away and doesn't move anything it DIM when saying the keywords. I then installed chrome w/extension to make sure I was doing everything correctly and it works fine flashes the icon 3 times and moves items.

**Comment by mlsof21** [comment]
I'm guessing it's because the extension uses the `chrome` namespace for extension interactions. I just ran into this issue on Firefox as well. I'm currently looking into the other browser compatibility

**Comment by ctrlcmdshft** [comment]
Awesome hope you get it working looking forward to using it with brave

**Comment by mlsof21** [comment]
Not yet, though I think it's the same issue that Firefox has in that the Web Speech API is only partially implemented. That means I might have to use an actual cloud service (Azure/AWS) in order to get transcription. There's a $ aspect there, so I'll have to see what that looks like.
