### ISSUE TITLE
Can't get to work with Mac

### ISSUE THREAD

**Issue by Shawful** [mlsof21/voice-dim#6]
Have you done any testing that this plugin works on a mac? And any idea how to confirm a voice command?  I don't see any visual notifications (like siri or alexa) to let me know that my laptop is listening for a command.  Am I missing something?

Thanks in advance!

**Comment by mlsof21** [comment]
Hi! I have tested in Mac. The first time you activate the shortcut in Chrome will ask for mic permissions. Then you should see a red record icon in the DIM tab. You should make sure the shortcut is set correctly in extension shortcuts (puzzle piece in extension toolbar, Manage extensions, 3 line menu in the top left, Keyboard shortcuts). Let me know if that works. I'm adding a troubleshooting section soon to help diagnose these issues.

**Comment by Shawful** [comment]
I think I remember allowing mic permissions.  I didn't realize that I needed to have DIM open, but that makes sense. I've added a custom Keyboard shortcut, but I'm not seeing a red record icon on the tab or in the browser page anywhere. Happy to help with troublshooting. :)

**Comment by mlsof21** [comment]
Whenever you hit your shortcut, you should a red recording icon in the DIM tab:
![image](https://user-images.githubusercontent.com/8508338/189997680-bef80f59-293b-449f-b592-8631b33b7e86.png)

**Comment by mlsof21** [comment]
This works for me without issue in Chrome on MacOS. Closing.

**Comment by Shawful** [comment]
I'm using version 105.0.5195.125 (Official Build) (x86_64) of chrome and it will not work for me.

When I enter my shortcut to activate DIM-voice, shift + CMD + 0, I see no visual cue to let me know if anything is activated on the tab for DIM.

Then when I try my shortcut to Start/Stop listening for DIM commands, shift + CMD + 9, I definitely don't see the red circle icon on the chrome tab.

Is there an order of operations I'm getting wrong? Or anything I've missed?

**Comment by mlsof21** [comment]
This is what I see when I click the lock symbol next to the url:
<img width="320" alt="image" src="https://user-images.githubusercontent.com/8508338/191143181-b4bf817f-f3ba-4917-a583-5ed321d1962c.png">

Do you see the microphone permission being granted?

**Comment by mlsof21** [comment]
This is also what I see in Privacy settings for MacOS:

<img width="493" alt="image" src="https://user-images.githubusercontent.com/8508338/191143467-1b3c3e67-3455-4896-8617-a74c4f477a57.png">

**Comment by mlsof21** [comment]
Could you do this? Open up devtools in DIM (press F12 or Opt+Cmd+J), then press the shortcut you have set, then post a screenshot of what you see in the console. That will be helpful.

**Comment by Shawful** [comment]
![image](https://user-images.githubusercontent.com/5322272/191146097-9176449f-c20a-41c7-b2fa-f7a3217e99e2.png)

**Comment by mlsof21** [comment]
And this is after pressing the shortcut. It doesn't seem like the background script is communicating with the actual extension in DIM. Navigate to the Extensions page again, then open the `service worker` link in the Voice DIM section:

<img width="402" alt="image" src="https://user-images.githubusercontent.com/8508338/191148590-951384f5-7cd2-4a68-ae65-83b1def2b15a.png">

Press the shortcut again, and see if this message pops up in the window:

<img width="312" alt="image" src="https://user-images.githubusercontent.com/8508338/191148670-133eb398-8621-487c-bb7f-f489cec2a557.png">

**Comment by Shawful** [comment]
After clicking the `service worker` link, the following was output in the console that popped up when I pressed the activate and then the listening shortcuts.

<img width="892" alt="image" src="https://user-images.githubusercontent.com/5322272/191606855-e3957464-4e15-4db4-b400-2857f9dd5901.png">

**Comment by Shawful** [comment]
Also, I noticed that the browser shows an Error in the top, right-hand corner with a message that Voice DIM is disabled. 

<img width="368" alt="image" src="https://user-images.githubusercontent.com/5322272/191607143-87dbdfa9-87a3-4985-a27f-36fa4a62346d.png">

When I click the notification and then click `Accept permissions`, the error in the browser persists as if nothing has changed.

<img width="323" alt="image" src="https://user-images.githubusercontent.com/5322272/191607275-24412667-5889-4065-ba53-24eb82880d67.png">

**Comment by mlsof21** [comment]
I haven't seen the `Error` message in the browser bar before, but the new permissions thing is expected. I updated the extension a few days ago.

In the previous comment, did you have a DIM tab open on the inventory page?

**Comment by mlsof21** [comment]
I've never had issues on Mac.
